### ISSUE TITLE
FTBFS on gutenprint 5.3+

### ISSUE THREAD

**Issue by OdyX** [blackfiveimaging/photoprint#3]
As reported on https://bugs.debian.org/915189; photoprint doesn't compile on gutenprint 5.3 with the following error:

```
gprinter.cpp: In member function 'virtual void GPrinter::GetImageableArea()':
gprinter.cpp:429:32: error: 'stp_get_papersize_by_name' was not declared in this scope
   const stp_papersize_t *paper=stp_get_papersize_by_name(papersize);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~
gprinter.cpp:429:32: note: suggested alternative: 'stp_list_get_item_by_name'
   const stp_papersize_t *paper=stp_get_papersize_by_name(papersize);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~
                                stp_list_get_item_by_name
```

Indeed, the `stp_get_papersize_by_name` function was removed in GutenPrint 5.3.

**Comment by Randrianasulu** [comment]
I found patch in FreeBSD's port system:
https://svnweb.freebsd.org/ports/head/print/photoprint/files/patch-gp_cppsupport_gprinter.cpp?view=log
